export const FETCH_META_START = 'FETCH_META_START';
export const FETCH_META_COMPLETE = 'FETCH_META_COMPLETE';
export const FETCH_META_FAILURE = 'FETCH_META_FAILURE';

export const INVOKE_METHOD_START = 'INVOKE_METHOD_START';
export const INVOKE_METHOD_SUCCESS = 'INVOKE_METHOD_SUCCESS';
export const INVOKE_METHOD_FAILURE = 'INVOKE_METHOD_FAILURE';
export const TOGGLE_METHOD = 'TOGGLE_METHOD';
